import mongoose from 'mongoose';
import Country from '../models/Country.js'; // Ensure correct path
import dotenv from 'dotenv';
import slugify from 'slugify';

dotenv.config();

const countries = [
  { name: 'Afghanistan', countryCode: 'AF', region: 'Asia' },
  { name: 'Albania', countryCode: 'AL', region: 'Europe' },
  { name: 'Algeria', countryCode: 'DZ', region: 'Africa' },
  { name: 'Andorra', countryCode: 'AD', region: 'Europe' },
  { name: 'Angola', countryCode: 'AO', region: 'Africa' },
  { name: 'Antigua and Barbuda', countryCode: 'AG', region: 'Americas' },
  { name: 'Argentina', countryCode: 'AR', region: 'Americas' },
  { name: 'Armenia', countryCode: 'AM', region: 'Asia' },
  { name: 'Australia', countryCode: 'AU', region: 'Oceania' },
  { name: 'Austria', countryCode: 'AT', region: 'Europe' },
  { name: 'Azerbaijan', countryCode: 'AZ', region: 'Asia' },
  { name: 'Bahamas', countryCode: 'BS', region: 'Americas' },
  { name: 'Bahrain', countryCode: 'BH', region: 'Asia' },
  { name: 'Bangladesh', countryCode: 'BD', region: 'Asia' },
  { name: 'Barbados', countryCode: 'BB', region: 'Americas' },
  { name: 'Belarus', countryCode: 'BY', region: 'Europe' },
  { name: 'Belgium', countryCode: 'BE', region: 'Europe' },
  { name: 'Belize', countryCode: 'BZ', region: 'Americas' },
  { name: 'Benin', countryCode: 'BJ', region: 'Africa' },
  { name: 'Bhutan', countryCode: 'BT', region: 'Asia' },
  { name: 'Bolivia', countryCode: 'BO', region: 'Americas' },
  { name: 'Bosnia and Herzegovina', countryCode: 'BA', region: 'Europe' },
  { name: 'Botswana', countryCode: 'BW', region: 'Africa' },
  { name: 'Brazil', countryCode: 'BR', region: 'Americas' },
  { name: 'Brunei', countryCode: 'BN', region: 'Asia' },
  { name: 'Bulgaria', countryCode: 'BG', region: 'Europe' },
  { name: 'Burkina Faso', countryCode: 'BF', region: 'Africa' },
  { name: 'Burundi', countryCode: 'BI', region: 'Africa' },
  { name: 'Cabo Verde', countryCode: 'CV', region: 'Africa' },
  { name: 'Cambodia', countryCode: 'KH', region: 'Asia' },
  { name: 'Cameroon', countryCode: 'CM', region: 'Africa' },
  { name: 'Canada', countryCode: 'CA', region: 'Americas' },
  { name: 'Central African Republic', countryCode: 'CF', region: 'Africa' },
  { name: 'Chad', countryCode: 'TD', region: 'Africa' },
  { name: 'Chile', countryCode: 'CL', region: 'Americas' },
  { name: 'China', countryCode: 'CN', region: 'Asia' },
  { name: 'Colombia', countryCode: 'CO', region: 'Americas' },
  { name: 'Comoros', countryCode: 'KM', region: 'Africa' },
  { name: 'Congo, Democratic Republic of the', countryCode: 'CD', region: 'Africa' },
  { name: 'Congo, Republic of the', countryCode: 'CG', region: 'Africa' },
  { name: 'Costa Rica', countryCode: 'CR', region: 'Americas' },
  { name: 'Croatia', countryCode: 'HR', region: 'Europe' },
  { name: 'Cuba', countryCode: 'CU', region: 'Americas' },
  { name: 'Cyprus', countryCode: 'CY', region: 'Europe' },
  { name: 'Czech Republic', countryCode: 'CZ', region: 'Europe' },
  { name: 'Denmark', countryCode: 'DK', region: 'Europe' },
  { name: 'Djibouti', countryCode: 'DJ', region: 'Africa' },
  { name: 'Dominica', countryCode: 'DM', region: 'Americas' },
  { name: 'Dominican Republic', countryCode: 'DO', region: 'Americas' },
  { name: 'Ecuador', countryCode: 'EC', region: 'Americas' },
  { name: 'Egypt', countryCode: 'EG', region: 'Africa' },
  { name: 'El Salvador', countryCode: 'SV', region: 'Americas' },
  { name: 'Equatorial Guinea', countryCode: 'GQ', region: 'Africa' },
  { name: 'Eritrea', countryCode: 'ER', region: 'Africa' },
  { name: 'Estonia', countryCode: 'EE', region: 'Europe' },
  { name: 'Eswatini', countryCode: 'SZ', region: 'Africa' },
  { name: 'Ethiopia', countryCode: 'ET', region: 'Africa' },
  { name: 'Fiji', countryCode: 'FJ', region: 'Oceania' },
  { name: 'Finland', countryCode: 'FI', region: 'Europe' },
  { name: 'France', countryCode: 'FR', region: 'Europe' },
  { name: 'Gabon', countryCode: 'GA', region: 'Africa' },
  { name: 'Gambia', countryCode: 'GM', region: 'Africa' },
  { name: 'Georgia', countryCode: 'GE', region: 'Asia' },
  { name: 'Germany', countryCode: 'DE', region: 'Europe' },
  { name: 'Ghana', countryCode: 'GH', region: 'Africa' },
  { name: 'Greece', countryCode: 'GR', region: 'Europe' },
  { name: 'Grenada', countryCode: 'GD', region: 'Americas' },
  { name: 'Guatemala', countryCode: 'GT', region: 'Americas' },
  { name: 'Guinea', countryCode: 'GN', region: 'Africa' },
  { name: 'Guinea-Bissau', countryCode: 'GW', region: 'Africa' },
  { name: 'Guyana', countryCode: 'GY', region: 'Americas' },
  { name: 'Haiti', countryCode: 'HT', region: 'Americas' },
  { name: 'Honduras', countryCode: 'HN', region: 'Americas' },
  { name: 'Hungary', countryCode: 'HU', region: 'Europe' },
  { name: 'Iceland', countryCode: 'IS', region: 'Europe' },
  { name: 'India', countryCode: 'IN', region: 'Asia' },
  { name: 'Indonesia', countryCode: 'ID', region: 'Asia' },
  { name: 'Iran', countryCode: 'IR', region: 'Asia' },
  { name: 'Iraq', countryCode: 'IQ', region: 'Asia' },
  { name: 'Ireland', countryCode: 'IE', region: 'Europe' },
  { name: 'Israel', countryCode: 'IL', region: 'Asia' },
  { name: 'Italy', countryCode: 'IT', region: 'Europe' },
  { name: 'Jamaica', countryCode: 'JM', region: 'Americas' },
  { name: 'Japan', countryCode: 'JP', region: 'Asia' },
  { name: 'Jordan', countryCode: 'JO', region: 'Asia' },
  { name: 'Kazakhstan', countryCode: 'KZ', region: 'Asia' },
  { name: 'Kenya', countryCode: 'KE', region: 'Africa' },
  { name: 'Kiribati', countryCode: 'KI', region: 'Oceania' },
  { name: 'Korea, North', countryCode: 'KP', region: 'Asia' },
  { name: 'Korea, South', countryCode: 'KR', region: 'Asia' },
  { name: 'Kuwait', countryCode: 'KW', region: 'Asia' },
  { name: 'Kyrgyzstan', countryCode: 'KG', region: 'Asia' },
  { name: 'Laos', countryCode: 'LA', region: 'Asia' },
  { name: 'Latvia', countryCode: 'LV', region: 'Europe' },
  { name: 'Lebanon', countryCode: 'LB', region: 'Asia' },
  { name: 'Lesotho', countryCode: 'LS', region: 'Africa' },
  { name: 'Liberia', countryCode: 'LR', region: 'Africa' },
  { name: 'Libya', countryCode: 'LY', region: 'Africa' },
  { name: 'Liechtenstein', countryCode: 'LI', region: 'Europe' },
  { name: 'Lithuania', countryCode: 'LT', region: 'Europe' },
  { name: 'Luxembourg', countryCode: 'LU', region: 'Europe' },
  { name: 'Madagascar', countryCode: 'MG', region: 'Africa' },
  { name: 'Malawi', countryCode: 'MW', region: 'Africa' },
  { name: 'Malaysia', countryCode: 'MY', region: 'Asia' },
  { name: 'Maldives', countryCode: 'MV', region: 'Asia' },
  { name: 'Mali', countryCode: 'ML', region: 'Africa' },
  { name: 'Malta', countryCode: 'MT', region: 'Europe' },
  { name: 'Marshall Islands', countryCode: 'MH', region: 'Oceania' },
  { name: 'Mauritania', countryCode: 'MR', region: 'Africa' },
  { name: 'Mauritius', countryCode: 'MU', region: 'Africa' },
  { name: 'Mexico', countryCode: 'MX', region: 'Americas' },
  { name: 'Micronesia', countryCode: 'FM', region: 'Oceania' },
  { name: 'Moldova', countryCode: 'MD', region: 'Europe' },
  { name: 'Monaco', countryCode: 'MC', region: 'Europe' },
  { name: 'Mongolia', countryCode: 'MN', region: 'Asia' },
  { name: 'Montenegro', countryCode: 'ME', region: 'Europe' },
  { name: 'Morocco', countryCode: 'MA', region: 'Africa' },
  { name: 'Mozambique', countryCode: 'MZ', region: 'Africa' },
  { name: 'Myanmar', countryCode: 'MM', region: 'Asia' },
  { name: 'Namibia', countryCode: 'NA', region: 'Africa' },
  { name: 'Nauru', countryCode: 'NR', region: 'Oceania' },
  { name: 'Nepal', countryCode: 'NP', region: 'Asia' },
  { name: 'Netherlands', countryCode: 'NL', region: 'Europe' },
  { name: 'New Zealand', countryCode: 'NZ', region: 'Oceania' },
  { name: 'Nicaragua', countryCode: 'NI', region: 'Americas' },
  { name: 'Niger', countryCode: 'NE', region: 'Africa' },
  { name: 'Nigeria', countryCode: 'NG', region: 'Africa' },
  { name: 'North Macedonia', countryCode: 'MK', region: 'Europe' },
  { name: 'Norway', countryCode: 'NO', region: 'Europe' },
  { name: 'Oman', countryCode: 'OM', region: 'Asia' },
  { name: 'Pakistan', countryCode: 'PK', region: 'Asia' },
  { name: 'Palau', countryCode: 'PW', region: 'Oceania' },
  { name: 'Panama', countryCode: 'PA', region: 'Americas' },
  { name: 'Papua New Guinea', countryCode: 'PG', region: 'Oceania' },
  { name: 'Paraguay', countryCode: 'PY', region: 'Americas' },
  { name: 'Peru', countryCode: 'PE', region: 'Americas' },
  { name: 'Philippines', countryCode: 'PH', region: 'Asia' },
  { name: 'Poland', countryCode: 'PL', region: 'Europe' },
  { name: 'Portugal', countryCode: 'PT', region: 'Europe' },
  { name: 'Qatar', countryCode: 'QA', region: 'Asia' },
  { name: 'Romania', countryCode: 'RO', region: 'Europe' },
  { name: 'Russia', countryCode: 'RU', region: 'Europe' },
  { name: 'Rwanda', countryCode: 'RW', region: 'Africa' },
  { name: 'Saint Kitts and Nevis', countryCode: 'KN', region: 'Americas' },
  { name: 'Saint Lucia', countryCode: 'LC', region: 'Americas' },
  { name: 'Saint Vincent and the Grenadines', countryCode: 'VC', region: 'Americas' },
  { name: 'Samoa', countryCode: 'WS', region: 'Oceania' },
  { name: 'San Marino', countryCode: 'SM', region: 'Europe' },
  { name: 'Sao Tome and Principe', countryCode: 'ST', region: 'Africa' },
  { name: 'Saudi Arabia', countryCode: 'SA', region: 'Asia' },
  { name: 'Senegal', countryCode: 'SN', region: 'Africa' },
  { name: 'Serbia', countryCode: 'RS', region: 'Europe' },
  { name: 'Seychelles', countryCode: 'SC', region: 'Africa' },
  { name: 'Sierra Leone', countryCode: 'SL', region: 'Africa' },
  { name: 'Singapore', countryCode: 'SG', region: 'Asia' },
  { name: 'Slovakia', countryCode: 'SK', region: 'Europe' },
  { name: 'Slovenia', countryCode: 'SI', region: 'Europe' },
  { name: 'Solomon Islands', countryCode: 'SB', region: 'Oceania' },
  { name: 'Somalia', countryCode: 'SO', region: 'Africa' },
  { name: 'South Africa', countryCode: 'ZA', region: 'Africa' },
  { name: 'South Sudan', countryCode: 'SS', region: 'Africa' },
  { name: 'Spain', countryCode: 'ES', region: 'Europe' },
  { name: 'Sri Lanka', countryCode: 'LK', region: 'Asia' },
  { name: 'Sudan', countryCode: 'SD', region: 'Africa' },
  { name: 'Suriname', countryCode: 'SR', region: 'Americas' },
  { name: 'Sweden', countryCode: 'SE', region: 'Europe' },
  { name: 'Switzerland', countryCode: 'CH', region: 'Europe' },
  { name: 'Syria', countryCode: 'SY', region: 'Asia' },
  { name: 'Taiwan', countryCode: 'TW', region: 'Asia' },
  { name: 'Tajikistan', countryCode: 'TJ', region: 'Asia' },
  { name: 'Tanzania', countryCode: 'TZ', region: 'Africa' },
  { name: 'Thailand', countryCode: 'TH', region: 'Asia' },
  { name: 'Togo', countryCode: 'TG', region: 'Africa' },
  { name: 'Tonga', countryCode: 'TO', region: 'Oceania' },
  { name: 'Trinidad and Tobago', countryCode: 'TT', region: 'Americas' },
  { name: 'Tunisia', countryCode: 'TN', region: 'Africa' },
  { name: 'Turkey', countryCode: 'TR', region: 'Asia' },
  { name: 'Turkmenistan', countryCode: 'TM', region: 'Asia' },
  { name: 'Tuvalu', countryCode: 'TV', region: 'Oceania' },
  { name: 'Uganda', countryCode: 'UG', region: 'Africa' },
  { name: 'Ukraine', countryCode: 'UA', region: 'Europe' },
  { name: 'United Arab Emirates', countryCode: 'AE', region: 'Asia' },
  { name: 'United Kingdom', countryCode: 'GB', region: 'Europe' },
  { name: 'United States', countryCode: 'US', region: 'Americas' },
  { name: 'Uruguay', countryCode: 'UY', region: 'Americas' },
  { name: 'Uzbekistan', countryCode: 'UZ', region: 'Asia' },
  { name: 'Vanuatu', countryCode: 'VU', region: 'Oceania' },
  { name: 'Vatican City', countryCode: 'VA', region: 'Europe' },
  { name: 'Venezuela', countryCode: 'VE', region: 'Americas' },
  { name: 'Vietnam', countryCode: 'VN', region: 'Asia' },
  { name: 'Yemen', countryCode: 'YE', region: 'Asia' },
  { name: 'Zambia', countryCode: 'ZM', region: 'Africa' },
  { name: 'Zimbabwe', countryCode: 'ZW', region: 'Africa' }
];

const seedCountries = async () => {
  try {
    await mongoose.connect(process.env.MONGO_DB_URL, {
      useNewUrlParser: true,
      useUnifiedTopology: true,
    });
    console.log('✅ Database connected');

    // Remove existing data to prevent duplicates
    await Country.deleteMany();
    console.log('⚠️ Existing country data removed');

    // Ensure country codes are stored in lowercase
    const formattedCountries = countries.map((country) => ({
      name: country.name,
      countryCode: country.countryCode.toLowerCase(),
      region: country.region,
      slug: slugify(country.name),
      flag: `https://flagcdn.com/w320/${country.countryCode.toLowerCase()}.png`,
    }));

    // Insert new countries
    await Country.insertMany(formattedCountries);
    console.log('✅ Countries seeded successfully');
  } catch (error) {
    console.error('❌ Error seeding countries:', error);
  } finally {
    mongoose.connection.close();
    console.log('🔌 Database connection closed');
  }
};

// Run the seeder
seedCountries();
