export const staticPages = [
  {
    path: '/',
    priority: 1,
    changefreq: 'daily',
  },
  {
    path: '/about',
    priority: 0.8,
    changefreq: 'monthly',
  },
  {
    path: '/contact',
    priority: 0.7,
    changefreq: 'monthly',
  },
  {
    path: '/privacy',
    priority: 0.6,
    changefreq: 'yearly',
  },
  {
    path: '/terms',
    priority: 0.6,
    changefreq: 'yearly',
  },
  {
    path: '/dcmapolicy',
    priority: 0.6,
    changefreq: 'yearly',
  },
  { path: '/tools', priority: 0.8, changefreq: 'weekly' },
  { path: '/tools/image-tools', priority: 0.7, changefreq: 'weekly' },
  { path: '/tools/pdf-tools', priority: 0.7, changefreq: 'weekly' },
  { path: '/tools/calculators', priority: 0.7, changefreq: 'weekly' },
  { path: '/tools/other-tools', priority: 0.6, changefreq: 'weekly' },
  { path: '/jobs', priority: 0.8, changefreq: 'weekly' },
  { path: '/time-and-date', priority: 0.8, changefreq: 'weekly' },
  { path: '/time-and-date/world-clock', priority: 0.7, changefreq: 'weekly' },
  { path: '/time-and-date/time-zone-converter', priority: 0.7, changefreq: 'weekly' },
  { path: '/time-and-date/calendar', priority: 0.7, changefreq: 'weekly' },
  { path: '/time-and-date/holidays', priority: 0.7, changefreq: 'weekly' },
  { path: '/time-and-date/calculators', priority: 0.6, changefreq: 'weekly' },
  { path: '/time-and-date/learn', priority: 0.6, changefreq: 'monthly' },
  { path: '/video-downloader', priority: 0.8, changefreq: 'weekly' },
  { path: '/video-downloader/youtube', priority: 0.7, changefreq: 'weekly' },
  { path: '/video-downloader/facebook', priority: 0.7, changefreq: 'weekly' },
  { path: '/video-downloader/instagram', priority: 0.7, changefreq: 'weekly' },
  { path: '/video-downloader/tiktok', priority: 0.7, changefreq: 'weekly' },
  { path: '/crypto', priority: 0.8, changefreq: 'hourly' },
  { path: '/metals', priority: 0.8, changefreq: 'hourly' },
  { path: '/forex', priority: 0.8, changefreq: 'hourly' },
  { path: '/news', priority: 0.8, changefreq: 'hourly' },
  { path: '/weather', priority: 0.8, changefreq: 'hourly' },
  { path: '/blogs', priority: 0.8, changefreq: 'hourly' },
  { path: '/biography', priority: 0.8, changefreq: 'weekly' },
  { path: '/sports', priority: 0.8, changefreq: 'weekly' },
  { path: '/sports/leagues', priority: 0.8, changefreq: 'weekly' },
  { path: '/sports/teams', priority: 0.8, changefreq: 'weekly' },
  { path: '/sports/players', priority: 0.8, changefreq: 'weekly' },
  {
    path: '/tools/image-tools/remove-watermark',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/image-tools/upscale-image',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/image-tools/image-to-svg',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/image-tools/blur-image',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/image-tools/image-histogram',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/image-tools/image-watermark',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/image-tools/adjust-brightness-contrast',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/image-tools/noise-reduction',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/image-tools/advanced-image-compressor',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/image-tools/image-to-ascii',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/image-tools/add-border',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/image-tools/add-text-to-image',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/image-tools/black-white-filter',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/image-tools/collage-maker',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/image-tools/colorize-photo',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/image-tools/compress-image',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/image-tools/crop-image',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/image-tools/heic-to-jpg',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/image-tools/image-format-converter',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/image-tools/image-splitter',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/image-tools/image-to-text',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/image-tools/pdf-to-jpg',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/image-tools/pixelate-image',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/image-tools/remove-background',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/image-tools/resize-image',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/image-tools/round-image',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/image-tools/view-metadata',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/pdf-tools/add-page-number-to-pdf',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/pdf-tools/bmp-to-pdf-converter',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/pdf-tools/compress-pdf-tool',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/pdf-tools/excel-to-pdf-tool',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/pdf-tools/extract-from-pdf',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/pdf-tools/extract-pdf-pages-tool',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/pdf-tools/high-resolution-tiff-to-pdf-converter',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/pdf-tools/jpg-to-pdf-converter',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/pdf-tools/merge-pdf-tool',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/pdf-tools/organize-pdf-tool',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/pdf-tools/pdf-to-bmp-converter',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/pdf-tools/pdf-to-csv',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/pdf-tools/pdf-to-png-converter',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/pdf-tools/pdf-to-tiff-converter',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/pdf-tools/pdf-to-txt-tool',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/pdf-tools/pdf-to-word',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/pdf-tools/pdf-to-zip-converter',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/pdf-tools/png-to-pdf-converter',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/pdf-tools/powerpoint-to-pdf-converter',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/pdf-tools/remove-pages-tool',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/pdf-tools/repair-pdf-tool',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/pdf-tools/rotate-pdf-tool',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/pdf-tools/txt-to-pdf-tool',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/physics/acceleration-calculator-with-charts',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/physics/arrow-speed-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/physics/astrophysics-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/physics/ballistic-coefficient-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/physics/biophysics-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/physics/car-crash-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/physics/car-jump-distance-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/physics/computational-physics-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/physics/condensed-matter-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/physics/cosmology-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/physics/electromagnetism-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/physics/energy-calculator-advanced',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/physics/fluid-dynamics-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/physics/free-fall-air-resistance-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/physics/general-relativity-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/physics/gravitational-force-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/physics/ground-speed-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/physics/harmonic-motion-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/physics/magnitude-acceleration-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/physics/momentum-collision-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/physics/nuclear-physics-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/physics/optics-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/physics/particle-physics-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/physics/plasma-physics-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/physics/polar-moment-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/physics/projectile-motion-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/physics/projectile-visualizer-advanced',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/physics/quantum-field-theory-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/physics/quantum-mechanics-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/physics/relativity-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/physics/rotational-dynamics-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/physics/statistical-mechanics-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/physics/suvat-calculator-advanced',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/physics/tension-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/physics/thermodynamics-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/physics/vector-resolver',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/physics/wave-mechanics-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/physics/work-energy-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/math/advanced-fraction-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/math/area-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/math/average-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/math/big-number-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/math/binary-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/math/circle-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/math/common-factor-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/math/confidence-interval-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/math/distance-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/math/exponent-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/math/factor-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/math/fraction-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/math/greatest-common-factor-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/math/half-life-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/math/hex-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/math/lcm-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/math/logarithm-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/math/long-division-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/math/matrix-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/math/mean-median-mode-range-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/math/number-sequence-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/math/p-value-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/math/percent-error-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/math/percentage-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/math/permutation-and-combination-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/math/prime-factorization-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/math/probability-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/math/pythagorean-theorem-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/math/quadratic-formula-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/math/random-number-generator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/math/ratio-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/math/right-triangle-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/math/root-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/math/rounding-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/math/sample-size-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/math/scientific-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/math/scientific-notation-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/math/slope-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/math/standard-deviation-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/math/statistics-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/math/surface-area-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/math/triangle-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/math/volume-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/math/z-score-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/health/anorexic-bmi-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/health/army-body-fat-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/health/bmi-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/health/bmr-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/health/body-surface-area-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/health/calories-burned-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/health/carbohydrate-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/health/fat-intake-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/health/healthy-weight-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/health/ideal-weight-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/health/lean-body-mass-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/health/one-rep-max-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/health/overweight-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/health/protein-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/health/tdee-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/biology/annealing-temperature-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/financial/401k-calculator-for-use-by-us-residents',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/financial/advance-debt-consolidation-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/financial/amortization-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/financial/annuity-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/financial/annuity-payout-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/financial/apr-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/financial/auto-lease-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/financial/auto-loan-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/financial/average-return-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/financial/bond-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/financial/budget-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/financial/business-loan-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/financial/canadian-mortgage-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/financial/cash-back-and-low-interest-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/financial/cd-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/financial/college-cost-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/financial/commission-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/financial/compound-interest-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/financial/credit-card-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/financial/credit-card-payoff-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/financial/debt-payoff-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/financial/debt-consolidation-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/financial/Depreciation-Calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/financial/Discount-Calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/financial/Down-Payment-Calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/financial/DTI-Ratio-Calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/financial/estate-tax-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/financial/FHA-Loan-Calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/financial/finance-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/financial/Future-Value-Calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/financial/house-affordability-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/financial/income-tax-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/financial/inflation-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/financial/interest-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/financial/interest-rate-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/financial/investment-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/financial/IRA-Calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/financial/IRR-Calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/financial/lease-Calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/financial/loan-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/financial/margin-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/financial/mortgage-amortization-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/financial/mortgage-payoff-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/financial/mortgage-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/financial/payback-period-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/financial/payment-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/financial/pension-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/financial/percent-off-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/financial/personal-loan-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/financial/present-value-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/financial/refinance-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/financial/rent-vs-buy-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/financial/rent-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/financial/rental-property-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/financial/repayment-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/financial/retirement-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/financial/rmd-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/financial/roi-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/financial/roth-ira-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/financial/salary-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/financial/savings-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/financial/simple-interest-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/financial/simplified-sales-tax-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/financial/social-security-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/financial/student-loan-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/financial/take-home-paycheck-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/financial/uk-mortgage-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/financial/va-mortgage-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/calculators/financial/vat-calculator',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/angle-converter',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/degrees-to-radians',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/radians-to-degrees',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/area-converter',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/acres-to-hectare',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/acres-to-square-feet',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/acres-to-square-miles',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/hectare-to-acres',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/square-feet-to-acres',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/square-feet-to-square-meter',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/square-feet-to-square-yards',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/square-meter-to-square-feet',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/square-miles-to-acres',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/square-yards-to-square-feet',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/case-converter',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/charge-converter',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/concentration-molar-converter',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/concentration-solution-converter',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/amps-to-milliamps-converter',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/current-converter',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/milliamps-to-amps-converter',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/data-storage-converter',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/gb-to-kb',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/gb-to-mb',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/gb-to-pb',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/gb-to-tb',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/kb-to-gb',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/kb-to-mb',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/kb-to-tb',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/mb-to-gb',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/mb-to-kb',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/mb-to-pb',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/mb-to-tb',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/pb-to-gb',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/pb-to-mb',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/pb-to-tb',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/tb-to-gb',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/tb-to-kb',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/tb-to-mb',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/tb-to-pb',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/data-transfer-converter',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/digital-image-resolution-converter',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/electric-conductance-converter',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/electric-conductivity-converter',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/electric-field-strength-converter',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/electric-potential-converter',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/electric-resistance-converter',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/electric-resistivity-converter',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/electrostatic-capacitance-converter',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/energy-converter',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/cal-to-j',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/cal-to-kcal',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/ftlb-to-nm',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/j-to-cal',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/j-to-kj',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/kcal-to-cal',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/kcal-to-kj',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/kj-to-j',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/kj-to-kcal',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/nm-to-ftlb',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/flow-mass-converter',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/flow-converter',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/force-converter',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/kg-to-newtons',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/lbs-to-newtons',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/newtons-to-kg',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/newtons-to-lbs',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/frequency-wavelength-converter',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/heat-density-converter',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/heat-flux-density-converter',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/heat-transfer-coefficient-converter',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/illumination_converter',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/inductance-converter',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/cm-to-feet',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/cm-to-inches',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/cm-to-km',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/cm-to-m',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/cm-to-mm',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/feet-to-cm',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/feet-to-inches',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/feet-to-meters',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/feet-to-miles',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/feet-to-mm',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/feet-to-yards',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/inches-to-cm',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/inches-to-feet',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/inches-to-meters',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/inches-to-mm',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/inches-to-yards',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/km-to-cm',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/km-to-m',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/km-to-miles',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/m-to-cm',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/m-to-km',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/m-to-mm',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/meters-to-feet',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/meters-to-inches',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/meters-to-miles',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/meters-to-yards',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/miles-to-feet',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/miles-to-km',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/miles-to-meters',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/miles-to-yards',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/mm-to-cm',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/mm-to-feet',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/mm-to-inches',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/mm-to-m',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/yards-to-feet',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/yards-to-inches',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/yards-to-meters',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/yards-to-miles',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/linear-charge-density-converter',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/linear-current-density-converter',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/luminance-converter',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/luminous-intensity-converter',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/magnetic-field-strength-converter',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/magnetic-flux-converter',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/magnetic-flux-density-converter',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/magnetomotive-force-converter',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/mass-flux-density-converter',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/binary-to-decimal',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/binary-to-hex',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/decimal-to-binary',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/decimal-to-hex',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/hex-to-binary',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/hex-to-decimal',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/numbers-converter',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/permeability-converter',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/btu-to-ton',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/hp-to-kw',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/hp-to-watts',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/kw-to-hp',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/power-converter',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/ton-to-btu',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/watts-to-hp',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/prefixes-converter',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/bar-to-psi',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/kpa-to-psi',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/pressure-converter',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/psi-to-bar',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/psi-to-kpa',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/radiation-converter',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/radiation-absorbed-dose-converter',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/radiation-activity-converter',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/radiation-exposure-converter',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/sound-converter',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/specific-heat-capacity-converter',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/fps-to-mph',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/knot-to-mph',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/kph-to-mph',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/mph-to-fps',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/mph-to-knot',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/mph-to-kph',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/mph-to-mps',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/mps-to-kph',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/mps-to-mph',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/speed-converter',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/surface-charge-density-converter',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/surface-current-density-converter',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/surface-tension-converter',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/celsius-to-fahrenheit',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/celsius-to-kelvin',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/fahrenheit-to-celsius',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/fahrenheit-to-kelvin',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/kelvin-to-celsius',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/kelvin-to-fahrenheit',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/temperature-converter',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/temperature-interval-converter',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/thermal-conductivity-converter',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/thermal-expansion-converter',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/thermal-resistance-converter',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/days-to-hours',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/days-to-minutes',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/days-to-months',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/days-to-seconds',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/days-to-years',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/hours-to-days',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/hours-to-minutes',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/milliseconds-to-seconds',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/minutes-to-days',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/minutes-to-hours',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/minutes-to-seconds',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/months-to-days',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/seconds-to-days',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/seconds-to-milliseconds',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/seconds-to-minutes',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/time-converter',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/years-to-days',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/typography-converter',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/volume-dry-converter',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/volume-lumber-converter',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/volume-charge-density-converter',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/cc-to-ml',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/cc-to-oz',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/cubic-feet-to-cubic-yards',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/cubic-feet-to-gallon',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/cubic-inches-to-gallons',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/cubic-inches-to-liters',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/cubic-yards-to-cubic-feet',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/cups-to-gallon',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/cups-to-liters',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/cups-to-ml',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/cups-to-pint',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/cups-to-quart',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/cups-to-tablespoons',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/gallon-to-cubic-feet',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/gallon-to-cups',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/gallon-to-ml',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/gallon-to-pints',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/gallon-to-quart',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/gallons-to-cubic-inches',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/gallons-to-liters',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/l-to-ml',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/liter-to-ounces',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/liters-to-cubic-inches',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/liters-to-cups',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/liters-to-gallons',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/liters-to-pints',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/liters-to-quarts',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/ml-to-cc',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/ml-to-cups',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/ml-to-gallon',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/ml-to-l',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/ml-to-pint',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/ml-to-teaspoon',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/ounces-to-liter',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/oz-to-cc',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/pint-to-cups',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/pint-to-ml',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/pints-to-gallon',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/pints-to-liters',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/quart-to-cups',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/quart-to-gallon',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/quarts-to-liters',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/tablespoons-to-cups',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/tablespoons-to-teaspoons',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/teaspoon-to-ml',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/teaspoons-to-tablespoons',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/volume-converter',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/g-to-kg',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/grams-to-milligrams',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/grams-to-ounces',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/grams-to-pounds',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/kg-to-g',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/kg-to-lbs',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/kg-to-oz',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/lbs-to-kg',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/lbs-to-stone',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/lbs-to-ton',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/milligrams-to-grams',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/ounces-to-grams',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/ounces-to-pounds',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/oz-to-kg',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/pounds-to-grams',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/pounds-to-ounces',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/stone-to-lbs',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/ton-to-lbs',
    priority: 0.5,
    changefreq: 'monthly',
  },
  {
    path: '/tools/other-tools/weight-mass-converter',
    priority: 0.5,
    changefreq: 'monthly',
  },
];

export const supportedCountries = {
  ae: 'ar',
  af: 'ps',
  al: 'sq',
  am: 'hy',
  ao: 'pt',
  ar: 'es',
  at: 'de',
  au: 'en',
  az: 'az',
  ba: 'bs',
  bd: 'bn',
  be: 'nl',
  bf: 'fr',
  bg: 'bg',
  bh: 'ar',
  bj: 'fr',
  bn: 'ms',
  br: 'pt',
  bt: 'dz',
  bw: 'en',
  by: 'be',
  ca: 'en',
  cd: 'fr',
  cf: 'fr',
  cg: 'fr',
  ch: 'de',
  ci: 'fr',
  cl: 'es',
  cm: 'fr',
  cn: 'zh',
  co: 'es',
  cv: 'pt',
  cy: 'el',
  cz: 'cs',
  de: 'de',
  dj: 'fr',
  dk: 'da',
  dz: 'ar',
  ee: 'et',
  eg: 'ar',
  er: 'ti',
  es: 'es',
  et: 'am',
  fi: 'fi',
  fj: 'en',
  fr: 'fr',
  ga: 'fr',
  ge: 'ka',
  gh: 'en',
  gm: 'en',
  gn: 'fr',
  gq: 'es',
  gr: 'el',
  gw: 'pt',
  hr: 'hr',
  hu: 'hu',
  id: 'id',
  ie: 'en',
  il: 'he',
  in: 'hi',
  iq: 'ar',
  ir: 'fa',
  is: 'is',
  it: 'it',
  jo: 'ar',
  jp: 'ja',
  ke: 'en',
  kh: 'km',
  ki: 'en',
  kr: 'ko',
  kw: 'ar',
  kz: 'kk',
  la: 'lo',
  lk: 'ta',
  lr: 'en',
  ls: 'en',
  lt: 'lt',
  lu: 'fr',
  lv: 'lv',
  ma: 'ar',
  md: 'ro',
  me: 'sr',
  mg: 'fr',
  mk: 'mk',
  ml: 'fr',
  mm: 'my',
  mn: 'mn',
  mt: 'mt',
  mu: 'en',
  mv: 'dv',
  mw: 'en',
  mx: 'es',
  my: 'ms',
  mz: 'pt',
  na: 'en',
  ne: 'fr',
  ng: 'en',
  nl: 'nl',
  no: 'no',
  np: 'ne',
  nr: 'na',
  nz: 'en',
  om: 'ar',
  pe: 'es',
  pg: 'en',
  ph: 'tl',
  pk: 'ur',
  pl: 'pl',
  pt: 'pt',
  qa: 'ar',
  ro: 'ro',
  rs: 'sr',
  ru: 'ru',
  rw: 'rw',
  sa: 'ar',
  sb: 'en',
  sc: 'en',
  sd: 'ar',
  se: 'sv',
  sg: 'en',
  si: 'sl',
  sk: 'sk',
  sl: 'en',
  sn: 'fr',
  so: 'so',
  ss: 'en',
  st: 'pt',
  sy: 'ar',
  sz: 'en',
  td: 'fr',
  th: 'th',
  tj: 'tg',
  tm: 'tk',
  tn: 'ar',
  to: 'to',
  tr: 'tr',
  tv: 'tv',
  tz: 'sw',
  ua: 'uk',
  ug: 'en',
  uk: 'en',
  us: 'en',
  uz: 'uz',
  vn: 'vi',
  vu: 'bi',
  ws: 'sm',
  ye: 'ar',
  za: 'en',
  zm: 'en',
  zw: 'en',
};
